### ISSUE TITLE
E_WARNING: Undefined variable $ID

### ISSUE THREAD

**Issue by Ilav1** [zioth/dokuwiki-autolink4#15]
Hi, I checked my Logfile and found the followong lines many times. I dont know how long these Warnings are shown... 

```
2023-12-14 22:57:09E_WARNING: Undefined variable $ID
.../lib/plugins/autolink4/syntax/regex.php(69)
    #0 .../lib/plugins/autolink4/syntax/regex.php(69): dokuwiki\ErrorHandler::errorHandler()
    #1 .../inc/Parsing/Parser.php(88): syntax_plugin_autolink4_regex->connectTo()
    #2 .../inc/Parsing/Parser.php(106): dokuwiki\Parsing\Parser->connectModes()
    #3 .../inc/parserutils.php(234): dokuwiki\Parsing\Parser->parse()
    #4 .../inc/parserutils.php(198): p_get_instructions()
    #5 .../inc/parserutils.php(158): p_cached_instructions()
    #6 ,,,/inc/Extension/PluginTrait.php(101): p_cached_output()
    #7 .../lib/plugins/revert/admin.php(55): dokuwiki\Extension\Plugin->locale_xhtml()
    #8 .../inc/template.php(188): admin_plugin_revert->html()
    #9 .../inc/Action/Admin.php(40): tpl_admin()
    #10 .../inc/template.php(100): dokuwiki\Action\Admin->tplContent()
    #11 [internal function]: tpl_content_core()
    #12 .../inc/Extension/Event.php(133): call_user_func_array()
    #13 .../inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger()
    #14 .../inc/template.php(85): dokuwiki\Extension\Event::createAndTrigger()
    #15 .../lib/tpl/mindthedark/main.php(97): tpl_content()
    #16 .../inc/actions.php(27): include('...')
    #17 .../doku.php(126): act_dispatch()
    #18 {main}

```

**Comment by zioth** [comment]
Fixed

**Comment by Ilav1** [comment]
I added your change to my dokuwiki..
Another error appears in helper.php:

```
2023-12-15 08:36:16
E_WARNING: Undefined variable $found
/var/lib/plugins/autolink4/helper.php(131)
    #0 /lib/plugins/autolink4/helper.php(131): dokuwiki\ErrorHandler::errorHandler()
    #1 /lib/plugins/autolink4/syntax/regex.php(88): helper_plugin_autolink4->getMatch()
    #2 /inc/parser/handler.php(284): syntax_plugin_autolink4_regex->handle()
    #3 /inc/Parsing/Lexer/Lexer.php(270): Doku_Handler->plugin()
    #4 /inc/Parsing/Lexer/Lexer.php(197): dokuwiki\Parsing\Lexer\Lexer->invokeHandler()
    #5 /inc/Parsing/Lexer/Lexer.php(147): dokuwiki\Parsing\Lexer\Lexer->dispatchTokens()
    #6 /inc/Parsing/Parser.php(109): dokuwiki\Parsing\Lexer\Lexer->parse()
    #7 /inc/parserutils.php(234): dokuwiki\Parsing\Parser->parse()
    #8 /inc/parserutils.php(198): p_get_instructions()
    #9 /inc/parserutils.php(525): p_cached_instructions()
    #10 /inc/parserutils.php(299): p_render_metadata()
    #11 /inc/indexer.php(147): p_get_metadata()
    #12 /inc/TaskRunner.php(199): idx_addPage()
    #13 /inc/TaskRunner.php(50): dokuwiki\TaskRunner->runIndexer()
    #14 /lib/exe/taskrunner.php(16): dokuwiki\TaskRunner->run()
    #15 {main}

```

@zioth 
Edit:

There are two different errors in the helper.php

Undefined array key "logwatch" and undefined variable $found
```

2023-12-15 09:05:22
E_WARNING: Undefined array key "logwatch"
/lib/plugins/autolink4/helper.php(121)
    #0 /lib/plugins/autolink4/helper.php(121): dokuwiki\ErrorHandler::errorHandler()
    #1 /lib/plugins/autolink4/syntax/regex.php(86): helper_plugin_autolink4->getMatch()
    #2 /inc/parser/handler.php(284): syntax_plugin_autolink4_regex->handle()
    #3 /inc/Parsing/Lexer/Lexer.php(270): Doku_Handler->plugin()
    #4 /inc/Parsing/Lexer/Lexer.php(197): dokuwiki\Parsing\Lexer\Lexer->invokeHandler()
    #5 /inc/Parsing/Lexer/Lexer.php(147): dokuwiki\Parsing\Lexer\Lexer->dispatchTokens()
    #6 /inc/Parsing/Parser.php(109): dokuwiki\Parsing\Lexer\Lexer->parse()
    #7 /inc/parserutils.php(234): dokuwiki\Parsing\Parser->parse()
    #8 /inc/parserutils.php(198): p_get_instructions()
    #9 /inc/parserutils.php(525): p_cached_instructions()
    #10 /inc/parserutils.php(299): p_render_metadata()
    #11 /inc/common.php(266): p_get_metadata()
    #12 /doku.php(97): pageinfo()
    #13 {main}
```

**Comment by zioth** [comment]
Fixed both issues. It looks like either you're forcing php into a stricter mode, or the latest version of dokuwiki is. I'll have to upgrade and see if there are more errors with my plugins.

**Comment by Ilav1** [comment]
@zioth 

I'm using PHP 8.1.2 an haven't any special PHP setting. 
My Dokuwiki Release is: 2023-04-04a "Jack Jackrum"


In the deprecated log there is the following error belong to autolink4:

`require(syntax.php) is deprecated. It was called from require() in /.../lib/plugins/autolink4/syntax/allwords.php:5 Autoloading should be used instead!`

I never looked into the dokuwiki log before. I hope these informations are helpful to get rid of the messages.

If I can help you anyway just tell me what I can to for you :)

**Comment by zioth** [comment]
I haven't upgraded doku or php for a few versions. When I have time, I should just do that and fix everything. Unfortunately for my doku plugins, I have a full-time job which takes most of my time. :)

But I'll add it to my list. Maybe I'll fix this during the holidays.

**Comment by Ilav1** [comment]
I still have these two logs in deprecated log after updating the plugin:

require(syntax.php) is deprecated. It was called from require() in /.../dokuwiki/lib/plugins/autolink4/syntax/allwords.php:5 Autoloading should be used instead!
2024-01-15 14:20:14require(syntax.php) is deprecated. It was called from require() in /.../dokuwiki/lib/plugins/autolink4/syntax/regex.php:2 Autoloading should be used instead!

Maybe you open this issue again?

**Comment by zioth** [comment]
I fixed this a week ago but forgot to push my changes. Those warnings should be gone now.

**Comment by Ilav1** [comment]
Ah, no problem. Thanks for your great plugins and work 👌😎
